server:
  servlet:
    context-path: /api
spring:
  application:
    name: spring-ai-demo

  config:
    import: "optional:configserver:"

  security:
    user:
      name: ai-dev-user
      password: yhw-maet-ddd
  datasource:
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS rai;
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled=true:
      path=/h2-console:
      settings:
        trace=false:
        web-allow-others=false:
  sql:
    init:
      mode: always
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: false

client:
  azure:
    speech:
      endpoint: https://test-speech-072023.cognitiveservices.azure.com/sts/v1.0/issuetoken
      subscription-key: 6e03d7598fa84e6c83a0c0533cbe5f19
      region: westeurope
    analytics:
      endpoint: https://test-ai-language-service.cognitiveservices.azure.com/
      subscription-key: 5ca10e361f524951ad91952b00ed14ef
      region: westeurope
    vision:
      endpoint: https://vision-demo-ai.cognitiveservices.azure.com/vision/v2.0/recognizeText
      subscription-key: 4dc83ea2d03848d5a4cab8ba35bf8116
      region: westeurope
speech:
  keyword-list: '["mandate","mandates","statement","statements","international payments","transaction","transactions"]'

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.rai.online.aidemo: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health, info, refresh"
  health:
    config:
      enabled: false
    db:
      enabled: false


